# Generated by Django 3.2.12 on 2023-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=3000)),
                ('price', models.IntegerField()),
                ('checkup', models.CharField(max_length=50)),
            ],
        ),
    ]
